name: Deploy to GitHub Pages

on:
  push:
    branches: [main]  # Change this to your branch name if it's not "main"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload site (excluding audio folder)
        uses: actions/upload-pages-artifact@v2
        with:
          path: .
          exclude: |
            audio/**

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
