name: Deploy to GitHub Pages

on:
  push:
    branches: [main]  # change to your default branch if needed

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout only needed files (exclude audio)
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            index.html
            script.js
            styles.css
          sparse-checkout-cone-mode: false

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload site
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
